/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum AggregationEnum {
    Sum = 'sum',
    Last = 'last'
}

export function AggregationEnumFromJSON(json: any): AggregationEnum {
    return AggregationEnumFromJSONTyped(json, false);
}

export function AggregationEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AggregationEnum {
    return json as AggregationEnum;
}

export function AggregationEnumToJSON(value?: AggregationEnum | null): any {
    return value as any;
}

