/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RoleEnum,
    RoleEnumFromJSON,
    RoleEnumFromJSONTyped,
    RoleEnumToJSON,
} from './';

/**
 * 
 * @export
 * @interface BulkCreateInviteRequest
 */
export interface BulkCreateInviteRequest {
    /**
     * 
     * @type {string}
     * @memberof BulkCreateInviteRequest
     */
    teamId: string;
    /**
     * 
     * @type {RoleEnum}
     * @memberof BulkCreateInviteRequest
     */
    role?: RoleEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkCreateInviteRequest
     */
    toEmails: Array<string>;
}

export function BulkCreateInviteRequestFromJSON(json: any): BulkCreateInviteRequest {
    return BulkCreateInviteRequestFromJSONTyped(json, false);
}

export function BulkCreateInviteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkCreateInviteRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'teamId': json['team_id'],
        'role': !exists(json, 'role') ? undefined : RoleEnumFromJSON(json['role']),
        'toEmails': json['to_emails'],
    };
}

export function BulkCreateInviteRequestToJSON(value?: BulkCreateInviteRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'team_id': value.teamId,
        'role': RoleEnumToJSON(value.role),
        'to_emails': value.toEmails,
    };
}


