/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerTokenResponse
 */
export interface CustomerTokenResponse {
    /**
     * 
     * @type {string}
     * @memberof CustomerTokenResponse
     */
    token: string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerTokenResponse
     */
    isNew: boolean;
}

export function CustomerTokenResponseFromJSON(json: any): CustomerTokenResponse {
    return CustomerTokenResponseFromJSONTyped(json, false);
}

export function CustomerTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerTokenResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
        'isNew': json['is_new'],
    };
}

export function CustomerTokenResponseToJSON(value?: CustomerTokenResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'is_new': value.isNew,
    };
}


