/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AggregationEnum,
    AggregationEnumFromJSON,
    AggregationEnumFromJSONTyped,
    AggregationEnumToJSON,
    RecordPeriodEnum,
    RecordPeriodEnumFromJSON,
    RecordPeriodEnumFromJSONTyped,
    RecordPeriodEnumToJSON,
} from './';

/**
 * 
 * @export
 * @interface FeatureSpec
 */
export interface FeatureSpec {
    /**
     * 
     * @type {string}
     * @memberof FeatureSpec
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureSpec
     */
    name: string;
    /**
     * 
     * @type {RecordPeriodEnum}
     * @memberof FeatureSpec
     */
    readonly recordPeriod: RecordPeriodEnum;
    /**
     * 
     * @type {AggregationEnum}
     * @memberof FeatureSpec
     */
    readonly aggregation: AggregationEnum;
    /**
     * 
     * @type {number}
     * @memberof FeatureSpec
     */
    maxLimit?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FeatureSpec
     */
    providerId?: string;
}

export function FeatureSpecFromJSON(json: any): FeatureSpec {
    return FeatureSpecFromJSONTyped(json, false);
}

export function FeatureSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'recordPeriod': RecordPeriodEnumFromJSON(json['record_period']),
        'aggregation': AggregationEnumFromJSON(json['aggregation']),
        'maxLimit': !exists(json, 'max_limit') ? undefined : json['max_limit'],
        'providerId': !exists(json, 'provider_id') ? undefined : json['provider_id'],
    };
}

export function FeatureSpecToJSON(value?: FeatureSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'max_limit': value.maxLimit,
        'provider_id': value.providerId,
    };
}


