/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PublicProfile,
    PublicProfileFromJSON,
    PublicProfileFromJSONTyped,
    PublicProfileToJSON,
} from './';

/**
 * 
 * @export
 * @interface Invite
 */
export interface Invite {
    /**
     * 
     * @type {string}
     * @memberof Invite
     */
    readonly id: string;
    /**
     * 
     * @type {PublicProfile}
     * @memberof Invite
     */
    readonly sentBy: PublicProfile;
    /**
     * 
     * @type {string}
     * @memberof Invite
     */
    sentToEmail: string;
    /**
     * 
     * @type {boolean}
     * @memberof Invite
     */
    isClaimed?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Invite
     */
    expiresAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Invite
     */
    readonly createdAt: Date;
}

export function InviteFromJSON(json: any): Invite {
    return InviteFromJSONTyped(json, false);
}

export function InviteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Invite {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'sentBy': PublicProfileFromJSON(json['sent_by']),
        'sentToEmail': json['sent_to_email'],
        'isClaimed': !exists(json, 'is_claimed') ? undefined : json['is_claimed'],
        'expiresAt': !exists(json, 'expires_at') ? undefined : (new Date(json['expires_at'])),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function InviteToJSON(value?: Invite | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sent_to_email': value.sentToEmail,
        'is_claimed': value.isClaimed,
        'expires_at': value.expiresAt === undefined ? undefined : (value.expiresAt.toISOString()),
    };
}


