/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Customer,
    CustomerFromJSON,
    CustomerFromJSONTyped,
    CustomerToJSON,
} from './';

/**
 * 
 * @export
 * @interface PaginatedCustomerList
 */
export interface PaginatedCustomerList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedCustomerList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCustomerList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCustomerList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Customer>}
     * @memberof PaginatedCustomerList
     */
    results?: Array<Customer>;
}

export function PaginatedCustomerListFromJSON(json: any): PaginatedCustomerList {
    return PaginatedCustomerListFromJSONTyped(json, false);
}

export function PaginatedCustomerListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCustomerList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(CustomerFromJSON)),
    };
}

export function PaginatedCustomerListToJSON(value?: PaginatedCustomerList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(CustomerToJSON)),
    };
}


