/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Provider,
    ProviderFromJSON,
    ProviderFromJSONTyped,
    ProviderToJSON,
} from './';

/**
 * 
 * @export
 * @interface PaginatedProviderList
 */
export interface PaginatedProviderList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedProviderList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedProviderList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedProviderList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Provider>}
     * @memberof PaginatedProviderList
     */
    results?: Array<Provider>;
}

export function PaginatedProviderListFromJSON(json: any): PaginatedProviderList {
    return PaginatedProviderListFromJSONTyped(json, false);
}

export function PaginatedProviderListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedProviderList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(ProviderFromJSON)),
    };
}

export function PaginatedProviderListToJSON(value?: PaginatedProviderList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(ProviderToJSON)),
    };
}


