/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Teammate,
    TeammateFromJSON,
    TeammateFromJSONTyped,
    TeammateToJSON,
} from './';

/**
 * 
 * @export
 * @interface PaginatedTeammateList
 */
export interface PaginatedTeammateList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedTeammateList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTeammateList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTeammateList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Teammate>}
     * @memberof PaginatedTeammateList
     */
    results?: Array<Teammate>;
}

export function PaginatedTeammateListFromJSON(json: any): PaginatedTeammateList {
    return PaginatedTeammateListFromJSONTyped(json, false);
}

export function PaginatedTeammateListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTeammateList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(TeammateFromJSON)),
    };
}

export function PaginatedTeammateListToJSON(value?: PaginatedTeammateList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(TeammateToJSON)),
    };
}


