/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Token,
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
} from './';

/**
 * 
 * @export
 * @interface PaginatedTokenList
 */
export interface PaginatedTokenList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedTokenList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTokenList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTokenList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Token>}
     * @memberof PaginatedTokenList
     */
    results?: Array<Token>;
}

export function PaginatedTokenListFromJSON(json: any): PaginatedTokenList {
    return PaginatedTokenListFromJSONTyped(json, false);
}

export function PaginatedTokenListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTokenList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(TokenFromJSON)),
    };
}

export function PaginatedTokenListToJSON(value?: PaginatedTokenList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(TokenToJSON)),
    };
}


