/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Subscription,
    SubscriptionFromJSON,
    SubscriptionFromJSONTyped,
    SubscriptionToJSON,
} from './';

/**
 * 
 * @export
 * @interface PaginatedSubscriptionList
 */
export interface PaginatedSubscriptionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedSubscriptionList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSubscriptionList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSubscriptionList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Subscription>}
     * @memberof PaginatedSubscriptionList
     */
    results?: Array<Subscription>;
}

export function PaginatedSubscriptionListFromJSON(json: any): PaginatedSubscriptionList {
    return PaginatedSubscriptionListFromJSONTyped(json, false);
}

export function PaginatedSubscriptionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedSubscriptionList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(SubscriptionFromJSON)),
    };
}

export function PaginatedSubscriptionListToJSON(value?: PaginatedSubscriptionList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(SubscriptionToJSON)),
    };
}


