/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedFeatureRequest
 */
export interface PatchedFeatureRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedFeatureRequest
     */
    providerId?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedFeatureRequest
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedFeatureRequest
     */
    display?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedFeatureRequest
     */
    tooltip?: string | null;
}

export function PatchedFeatureRequestFromJSON(json: any): PatchedFeatureRequest {
    return PatchedFeatureRequestFromJSONTyped(json, false);
}

export function PatchedFeatureRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedFeatureRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'providerId': !exists(json, 'provider_id') ? undefined : json['provider_id'],
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'display': !exists(json, 'display') ? undefined : json['display'],
        'tooltip': !exists(json, 'tooltip') ? undefined : json['tooltip'],
    };
}

export function PatchedFeatureRequestToJSON(value?: PatchedFeatureRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'provider_id': value.providerId,
        'slug': value.slug,
        'display': value.display,
        'tooltip': value.tooltip,
    };
}


