/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedFeatureSpecRequest
 */
export interface PatchedFeatureSpecRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedFeatureSpecRequest
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedFeatureSpecRequest
     */
    maxLimit?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedFeatureSpecRequest
     */
    providerId?: string;
}

export function PatchedFeatureSpecRequestFromJSON(json: any): PatchedFeatureSpecRequest {
    return PatchedFeatureSpecRequestFromJSONTyped(json, false);
}

export function PatchedFeatureSpecRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedFeatureSpecRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'maxLimit': !exists(json, 'max_limit') ? undefined : json['max_limit'],
        'providerId': !exists(json, 'provider_id') ? undefined : json['provider_id'],
    };
}

export function PatchedFeatureSpecRequestToJSON(value?: PatchedFeatureSpecRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'max_limit': value.maxLimit,
        'provider_id': value.providerId,
    };
}


