/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedProviderRequest
 */
export interface PatchedProviderRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedProviderRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedProviderRequest
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedProviderRequest
     */
    ownerId?: string;
}

export function PatchedProviderRequestFromJSON(json: any): PatchedProviderRequest {
    return PatchedProviderRequestFromJSONTyped(json, false);
}

export function PatchedProviderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedProviderRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'ownerId': !exists(json, 'owner_id') ? undefined : json['owner_id'],
    };
}

export function PatchedProviderRequestToJSON(value?: PatchedProviderRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'slug': value.slug,
        'owner_id': value.ownerId,
    };
}


