/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedSubscriptionRequest
 */
export interface PatchedSubscriptionRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedSubscriptionRequest
     */
    planId?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSubscriptionRequest
     */
    teamId?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedSubscriptionRequest
     */
    startAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedSubscriptionRequest
     */
    endAt?: Date | null;
}

export function PatchedSubscriptionRequestFromJSON(json: any): PatchedSubscriptionRequest {
    return PatchedSubscriptionRequestFromJSONTyped(json, false);
}

export function PatchedSubscriptionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedSubscriptionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'planId': !exists(json, 'plan_id') ? undefined : json['plan_id'],
        'teamId': !exists(json, 'team_id') ? undefined : json['team_id'],
        'startAt': !exists(json, 'start_at') ? undefined : (new Date(json['start_at'])),
        'endAt': !exists(json, 'end_at') ? undefined : (json['end_at'] === null ? null : new Date(json['end_at'])),
    };
}

export function PatchedSubscriptionRequestToJSON(value?: PatchedSubscriptionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'plan_id': value.planId,
        'team_id': value.teamId,
        'start_at': value.startAt === undefined ? undefined : (value.startAt.toISOString()),
        'end_at': value.endAt === undefined ? undefined : (value.endAt === null ? null : value.endAt.toISOString()),
    };
}


