/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedProviderRequest
 */
export interface PatchedProviderRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedProviderRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedProviderRequest
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedProviderRequest
     */
    authUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedProviderRequest
     */
    homeUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedProviderRequest
     */
    defaultPlan?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedProviderRequest
     */
    trialDays?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedProviderRequest
     */
    isCardRequired?: boolean;
}

export function PatchedProviderRequestFromJSON(json: any): PatchedProviderRequest {
    return PatchedProviderRequestFromJSONTyped(json, false);
}

export function PatchedProviderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedProviderRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'authUrl': !exists(json, 'auth_url') ? undefined : json['auth_url'],
        'homeUrl': !exists(json, 'home_url') ? undefined : json['home_url'],
        'defaultPlan': !exists(json, 'default_plan') ? undefined : json['default_plan'],
        'trialDays': !exists(json, 'trial_days') ? undefined : json['trial_days'],
        'isCardRequired': !exists(json, 'is_card_required') ? undefined : json['is_card_required'],
    };
}

export function PatchedProviderRequestToJSON(value?: PatchedProviderRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'slug': value.slug,
        'auth_url': value.authUrl,
        'home_url': value.homeUrl,
        'default_plan': value.defaultPlan,
        'trial_days': value.trialDays,
        'is_card_required': value.isCardRequired,
    };
}


