/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentIntentResponse
 */
export interface PaymentIntentResponse {
    /**
     * 
     * @type {string}
     * @memberof PaymentIntentResponse
     */
    clientSecret: string;
}

export function PaymentIntentResponseFromJSON(json: any): PaymentIntentResponse {
    return PaymentIntentResponseFromJSONTyped(json, false);
}

export function PaymentIntentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentIntentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clientSecret': json['client_secret'],
    };
}

export function PaymentIntentResponseToJSON(value?: PaymentIntentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'client_secret': value.clientSecret,
    };
}


