/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProviderRequest
 */
export interface ProviderRequest {
    /**
     * 
     * @type {string}
     * @memberof ProviderRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderRequest
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderRequest
     */
    ownerId: string;
}

export function ProviderRequestFromJSON(json: any): ProviderRequest {
    return ProviderRequestFromJSONTyped(json, false);
}

export function ProviderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'slug': json['slug'],
        'ownerId': json['owner_id'],
    };
}

export function ProviderRequestToJSON(value?: ProviderRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'slug': value.slug,
        'owner_id': value.ownerId,
    };
}


