/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum RecordPeriodEnum {
    Hourly = 'hourly',
    Daily = 'daily',
    Weekly = 'weekly',
    Monthly = 'monthly',
    Annually = 'annually'
}

export function RecordPeriodEnumFromJSON(json: any): RecordPeriodEnum {
    return RecordPeriodEnumFromJSONTyped(json, false);
}

export function RecordPeriodEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordPeriodEnum {
    return json as RecordPeriodEnum;
}

export function RecordPeriodEnumToJSON(value?: RecordPeriodEnum | null): any {
    return value as any;
}

