/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamAccess
 */
export interface TeamAccess {
    /**
     * 
     * @type {string}
     * @memberof TeamAccess
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamAccess
     */
    teamId: string;
    /**
     * 
     * @type {string}
     * @memberof TeamAccess
     */
    name?: string;
}

export function TeamAccessFromJSON(json: any): TeamAccess {
    return TeamAccessFromJSONTyped(json, false);
}

export function TeamAccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamAccess {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'teamId': json['team_id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function TeamAccessToJSON(value?: TeamAccess | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'team_id': value.teamId,
        'name': value.name,
    };
}


