/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamDetailRequest
 */
export interface TeamDetailRequest {
    /**
     * 
     * @type {string}
     * @memberof TeamDetailRequest
     */
    providerId?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamDetailRequest
     */
    name: string | null;
}

export function TeamDetailRequestFromJSON(json: any): TeamDetailRequest {
    return TeamDetailRequestFromJSONTyped(json, false);
}

export function TeamDetailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamDetailRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'providerId': !exists(json, 'provider_id') ? undefined : json['provider_id'],
        'name': json['name'],
    };
}

export function TeamDetailRequestToJSON(value?: TeamDetailRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'provider_id': value.providerId,
        'name': value.name,
    };
}


