/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum BillingPeriodEnum {
    Hourly = 'hourly',
    Daily = 'daily',
    Weekly = 'weekly',
    Monthly = 'monthly',
    Annually = 'annually'
}

export function BillingPeriodEnumFromJSON(json: any): BillingPeriodEnum {
    return BillingPeriodEnumFromJSONTyped(json, false);
}

export function BillingPeriodEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingPeriodEnum {
    return json as BillingPeriodEnum;
}

export function BillingPeriodEnumToJSON(value?: BillingPeriodEnum | null): any {
    return value as any;
}

