/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerPaymentIntentRequest
 */
export interface CustomerPaymentIntentRequest {
    /**
     * 
     * @type {string}
     * @memberof CustomerPaymentIntentRequest
     */
    planId: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerPaymentIntentRequest
     */
    teamId: string;
}

export function CustomerPaymentIntentRequestFromJSON(json: any): CustomerPaymentIntentRequest {
    return CustomerPaymentIntentRequestFromJSONTyped(json, false);
}

export function CustomerPaymentIntentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerPaymentIntentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'planId': json['plan_id'],
        'teamId': json['team_id'],
    };
}

export function CustomerPaymentIntentRequestToJSON(value?: CustomerPaymentIntentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'plan_id': value.planId,
        'team_id': value.teamId,
    };
}


