/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IDTokenExchangeRequest
 */
export interface IDTokenExchangeRequest {
    /**
     * 
     * @type {string}
     * @memberof IDTokenExchangeRequest
     */
    idToken: string;
}

export function IDTokenExchangeRequestFromJSON(json: any): IDTokenExchangeRequest {
    return IDTokenExchangeRequestFromJSONTyped(json, false);
}

export function IDTokenExchangeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IDTokenExchangeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'idToken': json['id_token'],
    };
}

export function IDTokenExchangeRequestToJSON(value?: IDTokenExchangeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id_token': value.idToken,
    };
}


