/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BillingPeriodEnum,
    BillingPeriodEnumFromJSON,
    BillingPeriodEnumFromJSONTyped,
    BillingPeriodEnumToJSON,
    StateEnum,
    StateEnumFromJSON,
    StateEnumFromJSONTyped,
    StateEnumToJSON,
} from './';

/**
 * 
 * @export
 * @interface Invoice
 */
export interface Invoice {
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    readonly id: string;
    /**
     * 
     * @type {BillingPeriodEnum}
     * @memberof Invoice
     */
    billingPeriod: BillingPeriodEnum;
    /**
     * 
     * @type {Date}
     * @memberof Invoice
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Invoice
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    readonly teamId: string;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    planName: string;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    readonly subscriptionId: string | null;
    /**
     * 
     * @type {StateEnum}
     * @memberof Invoice
     */
    state: StateEnum;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    stripePaymentId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    total: string;
}

export function InvoiceFromJSON(json: any): Invoice {
    return InvoiceFromJSONTyped(json, false);
}

export function InvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Invoice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'billingPeriod': BillingPeriodEnumFromJSON(json['billing_period']),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'teamId': json['team_id'],
        'planName': json['plan_name'],
        'subscriptionId': json['subscription_id'],
        'state': StateEnumFromJSON(json['state']),
        'stripePaymentId': !exists(json, 'stripe_payment_id') ? undefined : json['stripe_payment_id'],
        'total': json['total'],
    };
}

export function InvoiceToJSON(value?: Invoice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'billing_period': BillingPeriodEnumToJSON(value.billingPeriod),
        'plan_name': value.planName,
        'state': StateEnumToJSON(value.state),
        'stripe_payment_id': value.stripePaymentId,
        'total': value.total,
    };
}


