/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IssueCustomerTokenRequest
 */
export interface IssueCustomerTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof IssueCustomerTokenRequest
     */
    customerId?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueCustomerTokenRequest
     */
    customerEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueCustomerTokenRequest
     */
    customerSourceId?: string;
}

export function IssueCustomerTokenRequestFromJSON(json: any): IssueCustomerTokenRequest {
    return IssueCustomerTokenRequestFromJSONTyped(json, false);
}

export function IssueCustomerTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueCustomerTokenRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customerId': !exists(json, 'customer_id') ? undefined : json['customer_id'],
        'customerEmail': !exists(json, 'customer_email') ? undefined : json['customer_email'],
        'customerSourceId': !exists(json, 'customer_source_id') ? undefined : json['customer_source_id'],
    };
}

export function IssueCustomerTokenRequestToJSON(value?: IssueCustomerTokenRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customer_id': value.customerId,
        'customer_email': value.customerEmail,
        'customer_source_id': value.customerSourceId,
    };
}


