/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum OpEnum {
    Inc = 'inc',
    Dec = 'dec',
    Set = 'set',
    Reset = 'reset'
}

export function OpEnumFromJSON(json: any): OpEnum {
    return OpEnumFromJSONTyped(json, false);
}

export function OpEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpEnum {
    return json as OpEnum;
}

export function OpEnumToJSON(value?: OpEnum | null): any {
    return value as any;
}

