/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FeatureSpec,
    FeatureSpecFromJSON,
    FeatureSpecFromJSONTyped,
    FeatureSpecToJSON,
} from './';

/**
 * 
 * @export
 * @interface PaginatedFeatureSpecList
 */
export interface PaginatedFeatureSpecList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedFeatureSpecList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFeatureSpecList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFeatureSpecList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<FeatureSpec>}
     * @memberof PaginatedFeatureSpecList
     */
    results?: Array<FeatureSpec>;
}

export function PaginatedFeatureSpecListFromJSON(json: any): PaginatedFeatureSpecList {
    return PaginatedFeatureSpecListFromJSONTyped(json, false);
}

export function PaginatedFeatureSpecListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedFeatureSpecList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(FeatureSpecFromJSON)),
    };
}

export function PaginatedFeatureSpecListToJSON(value?: PaginatedFeatureSpecList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(FeatureSpecToJSON)),
    };
}


