/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedCustomerRequest
 */
export interface PatchedCustomerRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedCustomerRequest
     */
    sourceId?: string;
}

export function PatchedCustomerRequestFromJSON(json: any): PatchedCustomerRequest {
    return PatchedCustomerRequestFromJSONTyped(json, false);
}

export function PatchedCustomerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedCustomerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sourceId': !exists(json, 'source_id') ? undefined : json['source_id'],
    };
}

export function PatchedCustomerRequestToJSON(value?: PatchedCustomerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'source_id': value.sourceId,
    };
}


