/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicProfile
 */
export interface PublicProfile {
    /**
     * 
     * @type {string}
     * @memberof PublicProfile
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof PublicProfile
     */
    readonly email: string;
}

export function PublicProfileFromJSON(json: any): PublicProfile {
    return PublicProfileFromJSONTyped(json, false);
}

export function PublicProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicProfile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
    };
}

export function PublicProfileToJSON(value?: PublicProfile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


