/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RoleEnum,
    RoleEnumFromJSON,
    RoleEnumFromJSONTyped,
    RoleEnumToJSON,
} from './';

/**
 * 
 * @export
 * @interface Teammate
 */
export interface Teammate {
    /**
     * 
     * @type {string}
     * @memberof Teammate
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof Teammate
     */
    readonly customerId: string;
    /**
     * 
     * @type {RoleEnum}
     * @memberof Teammate
     */
    role: RoleEnum;
    /**
     * 
     * @type {string}
     * @memberof Teammate
     */
    readonly email: string;
}

export function TeammateFromJSON(json: any): Teammate {
    return TeammateFromJSONTyped(json, false);
}

export function TeammateFromJSONTyped(json: any, ignoreDiscriminator: boolean): Teammate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'customerId': json['customer_id'],
        'role': RoleEnumFromJSON(json['role']),
        'email': json['email'],
    };
}

export function TeammateToJSON(value?: Teammate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role': RoleEnumToJSON(value.role),
    };
}


