/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamAccessRequest
 */
export interface TeamAccessRequest {
    /**
     * 
     * @type {string}
     * @memberof TeamAccessRequest
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamAccessRequest
     */
    teamId: string;
    /**
     * 
     * @type {string}
     * @memberof TeamAccessRequest
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TeamAccessRequest
     */
    revoke?: boolean;
}

export function TeamAccessRequestFromJSON(json: any): TeamAccessRequest {
    return TeamAccessRequestFromJSONTyped(json, false);
}

export function TeamAccessRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamAccessRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'teamId': json['team_id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'revoke': !exists(json, 'revoke') ? undefined : json['revoke'],
    };
}

export function TeamAccessRequestToJSON(value?: TeamAccessRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'team_id': value.teamId,
        'name': value.name,
        'revoke': value.revoke,
    };
}


