/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Account,
    AccountFromJSON,
    AccountToJSON,
} from '../models';

/**
 * 
 */
export class AccountsApi extends runtime.BaseAPI {

    /**
     * Shortcut to `/accounts/v1/{{my customer id}}`.  Automatically creates a new customer account if one does not exist for the authenticated user.
     */
    async accountsV1MeRetrieveRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Account>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        const response = await this.request({
            path: `/accounts/v1/me/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountFromJSON(jsonValue));
    }

    /**
     * Shortcut to `/accounts/v1/{{my customer id}}`.  Automatically creates a new customer account if one does not exist for the authenticated user.
     */
    async accountsV1MeRetrieve(initOverrides?: RequestInit): Promise<Account> {
        const response = await this.accountsV1MeRetrieveRaw(initOverrides);
        return await response.value();
    }

}
