/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    PaginatedPlanList,
    PaginatedPlanListFromJSON,
    PaginatedPlanListToJSON,
} from '../models';

export interface PublicPlansV1ListRequest {
    limit?: number;
    offset?: number;
}

/**
 * 
 */
export class PublicApi extends runtime.BaseAPI {

    /**
     */
    async publicPlansV1ListRaw(requestParameters: PublicPlansV1ListRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<PaginatedPlanList>> {
        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/public/plans/v1/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedPlanListFromJSON(jsonValue));
    }

    /**
     */
    async publicPlansV1List(requestParameters: PublicPlansV1ListRequest, initOverrides?: RequestInit): Promise<PaginatedPlanList> {
        const response = await this.publicPlansV1ListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
