name: Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: Setup git
      run: |
        git config --global user.email "bot@ironplans.com"
        git config --global user.name "Iron Robot"
        
    - name: Setup project
      working-directory: ./browser
      run: |
        yarn install --frozen-lockfile
    
    - name: Release
      run: NODE_ENV=production yarn release
        
