name: Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: v16

    - name: Setup git
      run: |
        git config --global user.email "bot@ironplans.com"
        git config --global user.name "Iron Robot"
    - run: yarn install --frozen-lockfile
      working-directory: ./browser
    - name: Release
      working-directory: ./browser
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NODE_ENV: production
      run: yarn release
      
        
